### ISSUE TITLE
https://doh.n2o.pw/

### ISSUE THREAD

**Issue by shatlyktma** [AuroraDNS/AuroraDNS.github.io#1]
https://doh.n2o.pw/

**Comment by shatlyktma** [comment]
> https://doh.n2o.pw/

**Comment by mili-tan** [comment]
> 
> 
> > https://doh.n2o.pw/

Hello, unfortunately, this server doh.n2o.pw has been forced to deactivate due to the bankruptcy of the sponsor.
This list has been migrated. The current list has been deprecated and has not been updated for a long time.
And as the maintainer of ArashiDNS, our public server arashi.doh.pp.ua has received a huge amount of visits from the Turkmenistan network. I cannot confirm whether this is an attack. Can you tell me what happened in Turkmenistan?
